baseURL = "https://esoyke.github.io/simpleJAM"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2022 Soykeco Limited"
disableKinds = ["section"]

[outputs]
    home = ["HTML", "JSON"]